## format
##
# zones:
#   Your zone name:
#     regions:
#       - X,Y,X2,Y2  # STRING with 2 points comma separated and
#       - X,Y,X2,Y2  # second area under the same name. not every place fits in one single square, right?
#       - 42.2,-8.7,42.1,-8.6  # example for some area in Vigo, Spain
#     zoom:  # optional
#       in: 8  # Should define how close the zoom gets. More zoom implies more data to download! (paid account?)
#       out: 1  # (defaults to 1) defines how far the zoom gets
# map: # optional section
#  style: map_style  # defaults to atlas
#  provider: thunderforest  # Maps © www.thunderforest.com, Data © www.osm.org/copyright
zones:
  US:
    zoom:
      in: 14
    regions:
      - 49.246676,-124.848974,24.396308,-66.93457
  States:
    zoom:
      out: 14
      in: 17
    regions:
      - 49.002494,-124.848974,45.543541,-116.916031
      - 41,-109,37,-102
      - 48.34,-116.57,44.38,-103.55
  Metros:
    zoom:
      in: 19
    regions:
      - 47.737, -117.635, 47.614, -117.387
      - 47.734, -122.515, 47.491, -122.224
map:
  # make it make sense with your provider!
  style: atlas
  # valid providers: geoapify, thunderforest, cnig.es (or Spain; no token needed)
  provider: thunderforest
  # reduce image quality to 8bits from this level and on (default: 12. set 0 for no reduction; 1 for all )
  reduce: 12
database:
  atlas:
    filename: ~/Desktop/maps/atlas/map.db
    flat_files: ~/Desktop/maps/thunderforest/atlas/