## format
##
# zones:
#   Your zone name:
#     regions:
#       - X,Y,X2,Y2  # STRING with 2 points comma separated and
#       - X,Y,X2,Y2  # second area under the same name. not every place fits in one single square, right?
#       - 42.2,-8.7,42.1,-8.6  # example for some area in Vigo, Spain
#     zoom:  # optional
#       in: 8  # Should define how close the zoom gets. More zoom implies more data to download! (paid account?)
#       out: 1  # (defaults to 1) defines how far the zoom gets
# map: # optional section
#  style: map_style  # defaults to atlas
#  provider: thunderforest  # Maps © www.thunderforest.com, Data © www.osm.org/copyright
zones:
  US:
    zoom:
      out: 7
      in: 11
    regions:
      - 49.246676,-124.848974,24.396308,-66.93457
  PNW:
    zoom:
      out: 11
      in: 14
    regions:
      - 49.002494,-124.848974,45.543541,-116.916031
  Spokane:
    zoom:
      out: 14
      in: 20
    regions:
      - 47.737, -117.635, 47.614, -117.387
  Seattle:
    zoom:
      out: 14
      in: 20
    regions:
      - 47.734, -122.515, 47.491, -122.224
  Montana:
    zoom:
      out: 11
      in: 14
    regions:
      - 49.002494,-116.916031,44.358221,-104.039648
#  Vigo (Spain):
#    zoom:
#      out: 10
#      in: 16
#    regions:
#      - 42.24285,-8.78276,42.20617,-8.67122
#  Coruña (Spain):
#    zoom:
#      out: 10
#      in: 14
#    regions:
#      - 43.39103,-8.45354,43.33636,-8.37160
#  Portugal:
#    zoom:
#      out: 1
#      in: 13
#    regions:
#      - 42.28,-9.96,36.79,-6.50    # Continente
#      - 39.90,-31.47,36.89,-24.95  # Acores
#      - 33.27,-17.40,32.32,-16.04  # Madeira
map:
  style: atlas  # make it make sense with your provider!
  provider: thunderforest  # valid providers: geoapify, thunderforest, cnig.es (or Spain; no token needed)
  # reducing size is a good practice for small screens and easier on SDcard storage, faster copying and faster reading.
  reduce: 12  # reduce image quality to 8bits from this level and on (default: 12. set 0 for no reduction; 1 for all )
