sync:
  # Copy Portugal ones by Pete to my default folder (would also avoid re-downloading possible matches)
  - source: /media/psf/Home/Desktop/maps/thunderforest/atlas
    destination: /mnt/MAPS/maps/atlas

